### ISSUE TITLE
Chemdoodle bug on explorer

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#758]
Unable to draw rings on chemdoodle in explorer - hub

**Comment by PaulBarrett79** [comment]
Has this been fixed by Andy's chemdoodle changes?

**Comment by strets123** [comment]
yes should be, awaiting test deployment

**Comment by strets123** [comment]
deployed to chembiohub/hubtest

**Comment by aekhendry** [comment]
Not working on hub test I'm afraid. Explorer. Also note that in Hubtest for the Chemdoodle window to be active you must now first clean the board before it will become active

**Comment by aekhendry** [comment]
Still broken. I cant draw the rings reliably. At first selecting the rings just makes a single carbon bond. If I click around enough then eventually I might be able to start drawing a benzene or pentane ring. However, sometimes when clicked on draw benzene, it will draw a pentane ring. So even when it starts drawing rings it is still unreliable

**Comment by strets123** [comment]
Now fixed Explorer

**Comment by aekhendry** [comment]
Closer but I can still break it. I could draw rings, but then I tried to draw a wedged bond and it wouldn't let me. From then on it started behaving similarly to before, with buttons drawing the wrong thing etc. Hub explorer

**Comment by strets123** [comment]
marking as wontfix

**Comment by strets123** [comment]
Not fixable easily mark as wontfix

**Comment by KarenPorter** [comment]
Decision needed in that case.  Is this a limitation the user can live with if given the right information?  If so, how do we capture this limitation and inform user?  most appropriately via an FAQ?

**Comment by strets123** [comment]
I have added a message to the search window when using explorer - please test in hubtest on the single molecule add and the search pages

**Comment by aekhendry** [comment]
Works fine, but please replace message with the following text:

It looks like you are using Internet Explorer. For a better experience with ChemDoodle on ChemBio Hub we recommend using a different browser. Currently only the single bonds and manually typing atoms features are available in Explorer.

**Comment by strets123** [comment]
Changed text

**Comment by aekhendry** [comment]
Message is now not showing in IE10
